import 'package:ride_share/features/transport/domain/entities/vechile_intity.dart';

import 'assets.dart';
import 'enum.dart';

List<VehicleEntity> vehiclesFake= [
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
  VehicleEntity(
    name: 'BMW',
    image: Assets.imagesCar3Png,
    controlVehicle: ControlVehicle.Automatic,
    seats: 3,
    otherFeatures: 'Octane',
    awayFrom: 3000,
    durationAway: "3 m",
  ),
];